/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TengoRouteImport } from './routes/tengo'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as RepetidasRouteImport } from './routes/repetidas'
import { Route as PaisesRouteImport } from './routes/paises'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as FaltantesRouteImport } from './routes/faltantes'
import { Route as EspecialesRouteImport } from './routes/especiales'
import { Route as ComandosRouteImport } from './routes/comandos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaisesCodigoRouteImport } from './routes/paises.$codigo'

const TengoRoute = TengoRouteImport.update({
  id: '/tengo',
  path: '/tengo',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetidasRoute = RepetidasRouteImport.update({
  id: '/repetidas',
  path: '/repetidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesRoute = PaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaltantesRoute = FaltantesRouteImport.update({
  id: '/faltantes',
  path: '/faltantes',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialesRoute = EspecialesRouteImport.update({
  id: '/especiales',
  path: '/especiales',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosRoute = ComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesCodigoRoute = PaisesCodigoRouteImport.update({
  id: '/$codigo',
  path: '/$codigo',
  getParentRoute: () => PaisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comandos': typeof ComandosRoute
  '/especiales': typeof EspecialesRoute
  '/faltantes': typeof FaltantesRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/repetidas': typeof RepetidasRoute
  '/revision': typeof RevisionRoute
  '/tengo': typeof TengoRoute
  '/paises/$codigo': typeof PaisesCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comandos': typeof ComandosRoute
  '/especiales': typeof EspecialesRoute
  '/faltantes': typeof FaltantesRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/repetidas': typeof RepetidasRoute
  '/revision': typeof RevisionRoute
  '/tengo': typeof TengoRoute
  '/paises/$codigo': typeof PaisesCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comandos': typeof ComandosRoute
  '/especiales': typeof EspecialesRoute
  '/faltantes': typeof FaltantesRoute
  '/importar': typeof ImportarRoute
  '/paises': typeof PaisesRouteWithChildren
  '/repetidas': typeof RepetidasRoute
  '/revision': typeof RevisionRoute
  '/tengo': typeof TengoRoute
  '/paises/$codigo': typeof PaisesCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comandos'
    | '/especiales'
    | '/faltantes'
    | '/importar'
    | '/paises'
    | '/repetidas'
    | '/revision'
    | '/tengo'
    | '/paises/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comandos'
    | '/especiales'
    | '/faltantes'
    | '/importar'
    | '/paises'
    | '/repetidas'
    | '/revision'
    | '/tengo'
    | '/paises/$codigo'
  id:
    | '__root__'
    | '/'
    | '/comandos'
    | '/especiales'
    | '/faltantes'
    | '/importar'
    | '/paises'
    | '/repetidas'
    | '/revision'
    | '/tengo'
    | '/paises/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComandosRoute: typeof ComandosRoute
  EspecialesRoute: typeof EspecialesRoute
  FaltantesRoute: typeof FaltantesRoute
  ImportarRoute: typeof ImportarRoute
  PaisesRoute: typeof PaisesRouteWithChildren
  RepetidasRoute: typeof RepetidasRoute
  RevisionRoute: typeof RevisionRoute
  TengoRoute: typeof TengoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tengo': {
      id: '/tengo'
      path: '/tengo'
      fullPath: '/tengo'
      preLoaderRoute: typeof TengoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetidas': {
      id: '/repetidas'
      path: '/repetidas'
      fullPath: '/repetidas'
      preLoaderRoute: typeof RepetidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises': {
      id: '/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof PaisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faltantes': {
      id: '/faltantes'
      path: '/faltantes'
      fullPath: '/faltantes'
      preLoaderRoute: typeof FaltantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especiales': {
      id: '/especiales'
      path: '/especiales'
      fullPath: '/especiales'
      preLoaderRoute: typeof EspecialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos': {
      id: '/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof ComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises/$codigo': {
      id: '/paises/$codigo'
      path: '/$codigo'
      fullPath: '/paises/$codigo'
      preLoaderRoute: typeof PaisesCodigoRouteImport
      parentRoute: typeof PaisesRoute
    }
  }
}

interface PaisesRouteChildren {
  PaisesCodigoRoute: typeof PaisesCodigoRoute
}

const PaisesRouteChildren: PaisesRouteChildren = {
  PaisesCodigoRoute: PaisesCodigoRoute,
}

const PaisesRouteWithChildren =
  PaisesRoute._addFileChildren(PaisesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComandosRoute: ComandosRoute,
  EspecialesRoute: EspecialesRoute,
  FaltantesRoute: FaltantesRoute,
  ImportarRoute: ImportarRoute,
  PaisesRoute: PaisesRouteWithChildren,
  RepetidasRoute: RepetidasRoute,
  RevisionRoute: RevisionRoute,
  TengoRoute: TengoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
